added Medinovita
vuejs-in/companies-using-vuejs-in-India pull request #39
Opened 2020-04-02 12:45 UTC by anjali89r

2020-04-03 07:28 UTC, nimitbhargava commented
@anjali89r thanks for PR
Can you add your company in the alphabetical order.

2020-04-03 12:26 UTC, anjali89r commented
@nimitbhargava done

2020-04-03 13:26 UTC, vinayakkulkarni requested changes

2020-04-03 13:26 UTC, vinayakkulkarni commented on README.md
> +➖
this _ideally_ shouldn't be in the PR

2020-04-04 00:08 UTC, anjali89r commented on README.md
> +➖
corrected

2020-04-04 06:19 UTC, merged

2020-04-04 06:19 UTC, nimitbhargava commented
@anjali89r Thanks for your contribution 👍